sudo: false  # use container-based virtualization environment
language: node_js
node_js:
  - "6"  # Node.js LTS maintained until April 2019, https://github.com/nodejs/lts
  - "node"  # latest stable Node.js release
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - 'npm install -g bower grunt-cli'
  - 'bower install --config.interactive=false'
